language: java
sudo: required

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      env: OSX=10.12.1
      osx_image: xcode9.2

before_install:
  - echo "We are in before_install section"
  - echo "Starting before install"
  - echo "Showing pwd"
  - pwd
  - echo "Showing initial permissions with ls -la -a"
  - ls -la -a
  - echo "Changing permissions on the file ./gradlew"
  - ls -la -a
  - chmod +x gradlew
  - echo "Showing resulting permissions with ls -la -a"
  - ls -la -a
  - git ls-tree HEAD
#  - echo "Starting expliciltly ./gradlew assemble"
#  - chmod +x ./gradlew assemble

install:
  - echo "We are in install section"
  - chmod +x gradlew


before_script:
  - echo "We are in before_script section"
  - chmod +x gradlew

script:
  - echo "We are in script section"
  - ./gradlew clean build
