version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - cinst jdk9 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk9
  - SET PATH=C:\jdk9\bin;%PATH%
  - refreshenv
  - java -version

build_script:
  - gradlew.bat clean build

branches:
  only:
    - master