version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - java -version
  - cuninst jdk8 -y
  - cinst jdk9  -y
  - refreshenv
  - java -version

build_script:
  - gradlew.bat clean build

branches:
  only:
    - master